package Constants.sandbox;

/*Generated by MPS */


public class Person {
  public static final String first = "Kiarash";
  public static final String last = "Torkian";
  public static final String middle = "N/A";
}
