package Constants.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x3fef54592cfb4468L, 0xbd718b90191a56b9L, 0x1a2adf0900058431L, "Constants.structure.Constant"))) {
        return Collections.<ConceptEditor>singletonList(new Constant_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x3fef54592cfb4468L, 0xbd718b90191a56b9L, 0x1a2adf090005842cL, "Constants.structure.Constants"))) {
        return Collections.<ConceptEditor>singletonList(new Constants_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
